export const xAxis = ["a", "b", "c", "d", "e", "f", "g", "h"];
export const yAxis = ["8", "7", "6", "5", "4", "3", "2", "1"];

export const positionPieceMap = {
    '00' : 'rook_b.png',
    '10' : 'knight_b.png',
    '20' : 'bishop_b.png',
    '30' : 'queen_b.png',
    '40' : 'king_b.png',
    '50' : 'bishop_b.png',
    '60' : 'knight_b.png',
    '70' : 'rook_b.png',
    '01' : 'pawn_b.png',
    '11' : 'pawn_b.png',
    '21' : 'pawn_b.png',
    '31' : 'pawn_b.png',
    '41' : 'pawn_b.png',
    '51' : 'pawn_b.png',
    '61' : 'pawn_b.png',
    '71' : 'pawn_b.png',
    '07' : 'rook_w.png',
    '17' : 'knight_w.png',
    '27' : 'bishop_w.png',
    '37' : 'queen_w.png',
    '47' : 'king_w.png',
    '57' : 'bishop_w.png',
    '67' : 'knight_w.png',
    '77' : 'rook_w.png',
    '06' : 'pawn_w.png',
    '16' : 'pawn_w.png',
    '26' : 'pawn_w.png',
    '36' : 'pawn_w.png',
    '46' : 'pawn_w.png',
    '56' : 'pawn_w.png',
    '66' : 'pawn_w.png',
    '76' : 'pawn_w.png',
};